# Generated by Django 4.1.7 on 2023-02-17 14:20

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0002_alter_gymsession_end_time_alter_gymsession_padlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('days_valid', models.PositiveSmallIntegerField()),
                ('session_limit', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gympass',
            name='session_limit',
        ),
        migrations.AlterField(
            model_name='gympass',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='gympass',
            name='valid_from',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='gympass',
            name='valid_to',
            field=models.DateField(verbose_name='Valid to'),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='padlock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='gym.padlock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gympass',
            name='gym_pass_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gym.gympasstype'),
            preserve_default=False,
        ),
    ]
