# Generated by Django 4.1.7 on 2023-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_gympasstype_remove_gympass_session_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gympass',
            name='valid_to',
        ),
        migrations.AlterField(
            model_name='gympass',
            name='valid_from',
            field=models.DateField(verbose_name='Valid from'),
        ),
    ]
