# Generated by Django 4.1.7 on 2023-03-18 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0004_remove_gympass_valid_to_alter_gympass_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsession',
            name='gym_pass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='gym.gympass'),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
