# Generated by Django 4.1.7 on 2023-03-19 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0005_remove_gympass_user_gympass_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gympasstype',
            old_name='days_valid',
            new_name='valid_for',
        ),
        migrations.AddField(
            model_name='gympass',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gympass',
            name='valid_to',
            field=models.DateField(default='2023-03-19', verbose_name='Valid to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gympasstype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gympass',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_passes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='gympasstype',
            name='session_limit',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
