# Generated by Django 4.1.7 on 2023-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_rename_days_valid_gympasstype_valid_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gympass',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='gympass',
            name='token',
            field=models.CharField(default='asd', max_length=64),
            preserve_default=False,
        ),
    ]
