# Generated by Django 4.1.7 on 2023-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_remove_gympass_qr_code_gympass_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gympasstype',
            name='valid_for',
            field=models.DurationField(),
        ),
    ]
