# Generated by Django 4.1.7 on 2023-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_gympasstype_valid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gympass',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
