# Generated by Django 4.1.7 on 2023-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_gympass_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gympasstype',
            name='purchasable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gympasstype',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
