# Generated by Django 4.1.7 on 2023-03-22 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0010_gympasstype_purchasable_alter_gympasstype_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(null=True)),
                ('gym_pass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='gym.gympass')),
            ],
        ),
        migrations.AddField(
            model_name='padlock',
            name='number',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GymSession',
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='padlock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='gym.padlock'),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
