# Generated by Django 4.1.7 on 2023-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_rename_session_limit_gympasstype_visit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padlock',
            name='text',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gympasstype',
            unique_together={('name', 'price')},
        ),
    ]
