# Generated by Django 4.1.7 on 2023-04-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_alter_padlock_text_alter_gympasstype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padlock',
            name='padlock_id',
            field=models.TextField(),
        ),
    ]
