# Generated by Django 4.1.7 on 2023-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_alter_padlock_padlock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gympasstype',
            name='valid_for',
            field=models.DurationField(null=True),
        ),
    ]
