# Generated by Django 4.1.7 on 2023-03-25 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_remove_user_is_staff_remove_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.TextField(choices=[('google', 'google')])),
                ('provider_uid', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_providers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProviderAccount',
        ),
    ]
